config/routes.rb
Rails.application.routes.draw do
  resources :pages
  devise_for :users
  root 'trend#show'

  get 'trend' => 'trend#show'
  get 'timeline' => 'timeline#show'
  get 'tag_feed' => 'tag_feed#show'
  get '/application/search', to: 'application#search'
  get '/articles/search', to: 'articles#search'
  get '/articles/stocks', to: 'articles#stocks'
  get '/articles/stocks_search', to: 'articles#stocks_search'
  resources :articles do
    resources :stocks, only: [:create, :update, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users do
    get '/like', to: 'users#like'
    get '/private', to: 'users#private'
    get '/commentpage', to: 'users#commentpage'
  end
  resources :tags #do

  #resources :users ,only: [:create, :destroy]


  #get "show_articles" => "articles#show_articles"
  #get "following_tags" => "tag#following_tags"
  #resouces :articles do
    #resources :comments, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :stocks, dependent: :destroy
  has_many :users, through: :stocks
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes
  belongs_to :user
  has_many :comments

  acts_as_taggable
  acts_as_taggable_on :articles

# いいね機能実装のための記述
  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def stock_user(user_id)
    stocks.find_by(user_id: user_id)
  end

end

app/models/comment.rb
class Comment < ApplicationRecord

#アソシエーション
  belongs_to :user
  belongs_to :article

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ApplicationRecord
#アソシエーション
  belongs_to :user
# likecountの実装
  belongs_to :article, counter_cache: :likes_count
  validates :user_id, presence: true
  validates :article_id, presence: true
  validates_uniqueness_of :article_id, scope: :user_id
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/stock.rb
class Stock < ApplicationRecord

#アソシエーション
  belongs_to :user
  belongs_to :article

  def stock_user(user_id)
    stocks.find_by(user_id: user_id)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #アソシエーション
  has_many :stocks, dependent: :destroy
  has_many :articles, through: :stocks
  has_many :likes, dependent: :destroy
  has_many :articles, through: :likes
  has_many :articles
  has_many :comments
  # likescount
  has_many :likes, dependent: :destroy
  #フォロー機能
  acts_as_followable # フォロワー機能
  acts_as_follower   # フォロー機能

  #タグ機能
  acts_as_taggable
  acts_as_taggable_on :articles

  mount_uploader :image, ImageUploader

end

app/controllers/tag_feed_controller.rb
class TagFeedController < ApplicationController
layout "main"
before_action :move_to_session, except: :index

  def show
    @articles = Article.all.order(" updated_at DESC ").limit(20)
  end

def move_to_session
    redirect_to "/users/sign_in" unless user_signed_in?
end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  layout "main"

  before_action :move_to_session, except: :index

  def show
    @tag = params[:id]
    @tags = ActsAsTaggableOn::Tag.all
    @articles = Article.all
  end

  def move_to_session
    redirect_to "/users/sign_in" unless user_signed_in?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def qiita_markdown(markdown)
    processor = Qiita::Markdown::Processor.new(hostname: "example.com")
    processor.filters << HTML::Pipeline::ImageMaxWidthFilter
    processor.call(markdown)[:output].to_s.html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def form_posted_time(time)
    time_d = time + 9.hour
    time_d.strftime("%Y-%m-%d %H:%M ")
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/tag_feed_helper.rb
module TagFeedHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/timeline_helper.rb
module TimelineHelper
end

app/helpers/trend_helper.rb
module TrendHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tag_feed/show.html.haml
.tag_feed
  .allWrapper
    .container1
      .menu-bar
        .menu-items1
          .menu-icon1
            = image_tag "3-trend_icon.png", class:"trend_icon3" , alt:"トレンド"
          .menu-item1
            .item1-name
              = link_to("トレンド", trend_path, class: 'articles_font_trend3')

        .menu-items2
          .menu-icon2
            = image_tag "1-menubar-timeline.png", class:"menubar-timeline" , alt: "タイムライン"
          .menu-item2
            .item2-name
              = link_to("タイムライン", timeline_path, class: 'articles_font_timeline3')

        .menu-items3
          .menu-icon3
            = image_tag "3-menubar-tag_feed.png", class:"menu-bar-tag_feed3" , alt:"タグフィード"
          .menu-item3
            .item3-name
              = link_to("タグフィード", tag_feed_path, class: 'articles_font_tag-feed3')

      .main-view
        .main-item
          .main-header
            .main-label-icon1
              = image_tag "3-mainview.png", class:"trend_view", alt:"trend_view"
              .main-label1
                .label-article
                  タグフィード

        - article_ids = []
        - for article in @articles
          - for tag in article.tags
            - for user_tag in current_user.tags
              - if tag == user_tag
                - article_ids << article.id
                - newarray = article_ids.uniq
        - if newarray.blank?
        - else
          - for num in newarray
            - for article in @articles
              - if num == article.id
                .articles
                  .picture
                    /= image_tag "python_tag.png", class:"python_tags", alt:""
                  .article
                    .article__tags
                      %ul
                        - article.tags.each do |tag|
                          %li.tag
                            ●
                            = link_to tag.name, "/tags/#{tag.name}", class: "tag-link"
                    .time_article
                      .time
                        = "#{article.created_at.strftime('%-m月%d日')}"
                    .article__title
                      = link_to article.title, "/articles/#{article.id}", :target=>["_blank"], class: "title-text"
                    .article__data
                      - if article.user.image.blank?
                        = image_tag "no-image.png", class: "avatar_tag-feed", alt:""
                        = link_to article.user.name, "/#{article.user.name}", class: "author-name"
                      - else
                        = image_tag "#{article.user.image}", class: "avatar_tag-feed", alt:"プロフ画"
                        = link_to article.user.name, "/#{article.user.name}", class: "author-name"

      .a-side
        .p-home_ad
          広告
        .ranking-user
          .ra-user-bar
            .user-header
              .user-header-label
                ユーザーランキング
              .user-list-tab
                .user-list-tabitem1
                  累計
                .user-list-tabitem2
                .user-list-tabitem3
            .user-list-content
              .ra-user
                .ra-user-start
                .ra-user-icon
                .trophy
                  = image_tag "!gold!.png", class:"rank", alt:"number_one"
                  .gold-before
                .ra-user-image
                  = image_tag "https://qiita-image-store.s3.amazonaws.com/0/164189/profile-images/1491563384", size: "32x32",  alt:"プロフ画"
                .user-name
                  @shotyan
                .ra-user-count
                  552
                  .ra-user-contrib
                    Contributions

              .ra-user
                .ra-user-start
                .ra-user-icon
                .trophy
                  = image_tag "!silvar!.png", class:"rank", alt:"number_one"
                  .gold-before
                .ra-user-image
                  = image_tag "https://qiita-image-store.s3.amazonaws.com/0/164189/profile-images/1491563384", size: "32x32",  alt:"プロフ画"
                .user-name
                  @hihiman
                .ra-user-count
                  530
                  .ra-user-contrib
                    Contributions

              .ra-user
                .ra-user-start
                .ra-user-icon
                .trophy
                  = image_tag "!bronze!.png", class:"rank", alt:"number_one"
                  .gold-before
                .ra-user-image
                  = image_tag "https://qiita-image-store.s3.amazonaws.com/0/164189/profile-images/1491563384", size: "32x32",  alt:"プロフ画"
                .user-name
                  @nauhodo
                .ra-user-count
                  514
                  .ra-user-contrib
                    Contributions

              .ra-user
                .ra-user-start
                .ra-user-icon
                .trophy
                  = image_tag "!4!.png", class:"rank", alt:"number_one"
                  .gold-before
                .ra-user-image
                  = image_tag "https://qiita-image-store.s3.amazonaws.com/0/164189/profile-images/1491563384", size: "32x32",  alt:"プロフ画"
                .user-name
                  @gannzi-
                .ra-user-count
                  423
                  .ra-user-contrib
                    Contributions

              .ra-user
                .ra-user-start
                .ra-user-icon
                .trophy
                  = image_tag "!5!.png", class:"rank", alt:"number_one"
                  .gold-before
                .ra-user-image
                  = image_tag "https://qiita-image-store.s3.amazonaws.com/0/164189/profile-images/1491563384", size: "32x32",  alt:"プロフ画"
                .user-name
                  @akebono
                .ra-user-count
                  333
                  .ra-user-contrib
                    Contributions

              .ra-user
                .ra-user-start
                .ra-user-icon
                .trophy
                  = image_tag "!6!.png", class:"rank", alt:"number_one"
                  .gold-before
                .ra-user-image
                  = image_tag "https://qiita-image-store.s3.amazonaws.com/0/164189/profile-images/1491563384", size: "32x32",  alt:"プロフ画"
                .user-name
                  @coffee2
                .ra-user-count
                  320
                  .ra-user-contrib
                    Contributions

              .ra-user
                .ra-user-start
                .ra-user-icon
                .trophy
                  = image_tag "!7!.png", class:"rank", alt:"number_one"
                  .gold-before
                .ra-user-image
                  = image_tag "https://qiita-image-store.s3.amazonaws.com/0/164189/profile-images/1491563384", size: "32x32",  alt:"プロフ画"
                .user-name
                  @banana3
                .ra-user-count
                  309
                  .ra-user-contrib
                    Contributions

              .ra-user
                .ra-user-start
                .ra-user-icon
                .trophy
                  = image_tag "!8!.png", class:"rank", alt:"number_one"
                  .gold-before
                .ra-user-image
                  = image_tag "https://qiita-image-store.s3.amazonaws.com/0/164189/profile-images/1491563384", size: "32x32",  alt:"プロフ画"
                .user-name
                  @sos_man
                .ra-user-count
                  209
                  .ra-user-contrib
                    Contributions

              .ra-user
                .ra-user-start
                .ra-user-icon
                .trophy
                  = image_tag "!9!.png", class:"rank", alt:"number_one"
                  .gold-before
                .ra-user-image
                  = image_tag "https://qiita-image-store.s3.amazonaws.com/0/164189/profile-images/1491563384", size: "32x32",  alt:"プロフ画"
                .user-name
                  @yarima9
                .ra-user-count
                  190
                  .ra-user-contrib
                    Contributions

              .ra-user
                .ra-user-start
                .ra-user-icon
                .trophy
                  = image_tag "!10!.png", class:"rank", alt:"number_one"
                  .gold-before
                .ra-user-image
                  = image_tag "https://qiita-image-store.s3.amazonaws.com/0/164189/profile-images/1491563384", size: "32x32",  alt:"プロフ画"
                .user-name
                  @aa-chan
                .ra-user-count
                  140
                  .ra-user-contrib
                    Contributions

            .container-body-right
              .container-body