config/routes.rb
Rails.application.routes.draw do
  resources :pages
  devise_for :users
  root 'trend#show'

  get 'trend' => 'trend#show'
  get 'timeline' => 'timeline#show'
  get 'tag_feed' => 'tag_feed#show'
  get '/application/search', to: 'application#search'
  get '/articles/search', to: 'articles#search'
  get '/articles/stocks', to: 'articles#stocks'
  get '/articles/stocks_search', to: 'articles#stocks_search'
  resources :articles do
    resources :stocks, only: [:create, :update, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users do
    get '/like', to: 'users#like'
    get '/private', to: 'users#private'
    get '/commentpage', to: 'users#commentpage'
  end
  resources :tags #do

  #resources :users ,only: [:create, :destroy]


  #get "show_articles" => "articles#show_articles"
  #get "following_tags" => "tag#following_tags"
  #resouces :articles do
    #resources :comments, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #アソシエーション
  has_many :stocks, dependent: :destroy
  has_many :articles, through: :stocks
  has_many :likes, dependent: :destroy
  has_many :articles, through: :likes
  has_many :articles
  has_many :comments
  # likescount
  has_many :likes, dependent: :destroy
  #フォロー機能
  acts_as_followable # フォロワー機能
  acts_as_follower   # フォロー機能

  #タグ機能
  acts_as_taggable
  acts_as_taggable_on :articles

  mount_uploader :image, ImageUploader

end

app/controllers/User/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/User/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/User/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/User/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/User/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/User/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  layout "main"

  before_action :move_to_session, except: :index

  def show
    @user = User.find(params[:id])
    @id = @user.id
    @articles = Article.all
  end

  def like
    @user = User.find(params[:user_id])
    @id = @user.id
    @articles = Article.all
  end

  def private
    @user = User.find(params[:user_id])
    @id = @user.id
    @articles = Article.all
  end

  def commentpage
    @user = User.find(params[:user_id])
    @id = @user.id
    @articles = Article.all
  end

  def update
    @user = current_user
    judge = params[:judge]

    if judge == "0"
      @user.update(user_params)
      @tags = params[:tag]
      @tag = params[:this_tag]
    else
      @user.update(user_image_params)
      redirect_to action: :show
    end
  end

  private
  def user_params
    params.permit(
      :name,
      :email
    ).merge(tag_list: params[:tag])
  end

  def user_image_params
    params.permit(
      :name,
      :email
    ).merge(image: params[:user][:image])
  end

  def move_to_session
    redirect_to "/users/sign_in" unless user_signed_in?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/commentpage.html.haml
.mypage-container
  .container-body
    .container-body-left
      .profile
        .profile__avatar
          - if @user.image.blank?
            = image_tag "no-image.png", class: "avatar", alt:""
          - else
            = image_tag "#{current_user.image}", class: "avatar", alt:"プロフ画"
          .profile__update
        .profile__my-name
          .full-name
            = @user.name
        .profile__tags-info
          .tag-header
            フォロー中のタグ
            - tags = []
            - for tagging in current_user.taggings
              - tags << tagging.tag.name
          %ul
            - tags.each do |tag|
              %li
                = tag

    .container-body-right
      .chart
      .chart-tab
        %ul
          %li
            .count
              - count = []
              - for article in @articles
                - if article.user == @user
                  - count << article.id
                  - number = count.length
              - if number.blank?
                =0
              - else
                = number
            .count-title
              Items
          %li
            .count
              0
            .count-title
              Contribution
          %li
            .count
              0
            .count-title
              Followers
      / = render 'users/recent-articles'
      .article-tab-comment
        %ul
          %li
            = link_to '投稿一覧', user_path(id: @id), method: :get, class: "no_line_color_blue"
          %li
            = link_to  'いいねした投稿', user_like_path(user_id: @id), method: :get, class: "no_line_color_blue"
          %li
            = link_to '限定共有投稿', user_private_path(user_id: @id), method: :get, class: "no_line_color_blue"
          %li--comment
            = link_to 'コメント', user_commentpage_path(user_id: @id), method: :get, class: "no_line_color_blue"

app/views/users/like.html.haml
.mypage-container
  .container-body
    .container-body-left
      .profile
        .profile__avatar
          - if @user.image.blank?
            = image_tag "no-image.png", class: "avatar", alt:""
          - else
            = image_tag "#{current_user.image}", class: "avatar", alt:"プロフ画"
          .profile__update
        .profile__my-name
          .full-name
            = @user.name
        .profile__tags-info
          .tag-header
            フォロー中のタグ
            - tags = []
            - for tagging in current_user.taggings
              - tags << tagging.tag.name
          %ul
            - tags.each do |tag|
              %li
                = tag

    .container-body-right
      .chart
      .chart-tab
        %ul
          %li
            .count
              - count = []
              - for article in @articles
                - if article.user == @user
                  - count << article.id
                  - number = count.length
              - if number.blank?
                =0
              - else
                = number
            .count-title
              Items
          %li
            .count
              0
            .count-title
              Contribution
          %li
            .count
              0
            .count-title
              Followers
      .article-tab-like
        %ul
          %li
            = link_to '投稿一覧', user_path(id: @id), method: :get, class: "no_line_color_blue"
          %li--like
            = link_to  'いいねした投稿', user_like_path(user_id: @id), method: :get, class: "no_line_color_blue"
          %li
            = link_to '限定共有投稿', user_private_path(user_id: @id), method: :get, class: "no_line_color_blue"
          %li
            = link_to 'コメント', user_commentpage_path(user_id: @id), method: :get, class: "no_line_color_blue"
      .articles
        - @articles.each do |article|
          - article.likes.each do |like|
            - if like.user_id == @user.id
              .article_area
                .my_picture
                  - if article.user.image.blank?
                    = image_tag "no-image.png", size: "48x48", alt:"", class: "author-avatar"
                  - else
                    = image_tag "#{article.user.image}", size: "48x48", alt:"プロフ画", class: "author-avatar"
                .article
                  .article__data
                    %span.author-name
                      = link_to article.user.name, "/#{article.user.name}", class: "author-name", class: "no_line_color_blue"
                    %span.date.no_line_color_blue
                      が
                      = "#{article.created_at.strftime('%-m月%d日')}"
                      に投稿
                  .article__title
                    = link_to article.title, "/articles/#{article.id}", :target=>["_blank"], class: "title-text", class: "no_line_color_blue"
                  .article__tags
                    %ul
                    - article.tags.each do |tag|
                      %li
                        = link_to tag.name, "/tags/#{tag.name}", class: "tag-name", class: "no_line_color_gray"

app/views/users/private.html.haml
.mypage-container
  .container-body
    .container-body-left
      .profile
        .profile__avatar
          - if @user.image.blank?
            = image_tag "no-image.png", class: "avatar", alt:""
          - else
            = image_tag "#{current_user.image}", class: "avatar", alt:"プロフ画"
          .profile__update
        .profile__my-name
          .full-name
            = @user.name
        .profile__tags-info
          .tag-header
            フォロー中のタグ
            - tags = []
            - for tagging in current_user.taggings
              - tags << tagging.tag.name
          %ul
            - tags.each do |tag|
              %li
                = tag
    .container-body-right
      .chart
      .chart-tab
        %ul
          %li
            .count
              - count = []
              - for article in @articles
                - if article.user == @user
                  - count << article.id
                  - number = count.length
              - if number.blank?
                =0
              - else
                = number
            .count-title
              Items
          %li
            .count
              0
            .count-title
              Contribution
          %li
            .count
              0
            .count-title
              Followers
      / = render 'users/recent-articles'
      .article-tab-onlypage
        %ul
          %li
            = link_to '投稿一覧', user_path(id: @id), method: :get, class: "no_line_color_blue"
          %li
            = link_to  'いいねした投稿', user_like_path(user_id: @id), method: :get, class: "no_line_color_blue"
          %li--onlypage
            = link_to '限定共有投稿', user_private_path(user_id: @id), method: :get, class: "no_line_color_blue"
          %li
            = link_to 'コメント', user_commentpage_path(user_id: @id), method: :get, class: "no_line_color_blue"

app/views/users/show.html.haml
.mypage-container
  .container-body
    .container-body-left
      .profile
        .profile__avatar
          - if @user.image.blank?
            = image_tag "no-image.png", class: "avatar", alt:""
          - else
            = image_tag "#{@user.image}", class: "avatar", alt:"プロフ画"
        - if @user.id == current_user.id
          .profile__update
            = form_for @user,:url => {:action => 'update'} do |f|
              = f.file_field :image
              %br/
              = f.submit 'set profile picture'

        .profile__my-name
          .full-name
            = @user.name
        .profile__tags-info
          .tag-header
            フォロー中のタグ
            - tags = []
            - for tagging in @user.taggings
              - tags << tagging.tag.name
          %ul
            - tags.each do |tag|
              %li
                = tag
    .container-body-right

      .chart
      .chart-tab
        %ul
          %li
            .count
              - count = []
              - for article in @articles
                - if article.user == @user
                  - count << article.id
                  - number = count.length
              - if number.blank?
                =0
              - else
                = number
            .count-title
              Items
          %li
            .count
              0
            .count-title
              Contribution
          %li
            .count
              0
            .count-title
              Followers

      .article-tab-recent
        %ul
          %li--recent
            = link_to '投稿一覧', user_path, method: :get, class: "no_line_color_blue"
          %li
            = link_to  'いいねした投稿', user_like_path(user_id: @id), method: :get, class: "no_line_color_blue"
          %li
            = link_to '限定共有投稿', user_private_path(user_id: @id), method: :get, class: "no_line_color_blue"
          %li
            = link_to 'コメント', user_commentpage_path(user_id: @id), method: :get, class: "no_line_color_blue"
      .articles
        - @articles.each do |article|
          - if article.user == @user
            .article_area
              .my_picture
                - if article.user.image.blank?
                  = image_tag "no-image.png", size: "48x48", alt:"", class: "author-avatar"
                - else
                  = image_tag "#{article.user.image}", size: "48x48", alt:"プロフ画", class: "author-avatar"
              .article
                .article__data
                  %span.author-name
                    = link_to article.user.name, "/#{article.user.name}", class: "author-name", class: "no_line_color_blue"
                  %span.date.no_line_color_blue
                    が
                    = "#{article.created_at.strftime('%-m月%d日')}"
                    に投稿
                .article__title
                  = link_to article.title, "/articles/#{article.id}", :target=>["_blank"], class: "title-text", class: "no_line_color_blue"
                .article__tags
                  %ul
                  - article.tags.each do |tag|
                    %li
                      = link_to tag.name, "/tags/#{tag.name}", class: "tag-name", class: "no_line_color_gray"

app/views/users/update.js.erb
$("#tag-follow-btn").html("<%= j(render partial: 'tags/tag_follow', locals: { tags: @tags, tag: @tag }) %>")