config/routes.rb
Rails.application.routes.draw do
  resources :pages
  devise_for :users
  root 'trend#show'

  get 'trend' => 'trend#show'
  get 'timeline' => 'timeline#show'
  get 'tag_feed' => 'tag_feed#show'
  get '/application/search', to: 'application#search'
  get '/articles/search', to: 'articles#search'
  get '/articles/stocks', to: 'articles#stocks'
  get '/articles/stocks_search', to: 'articles#stocks_search'
  resources :articles do
    resources :stocks, only: [:create, :update, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users do
    get '/like', to: 'users#like'
    get '/private', to: 'users#private'
    get '/commentpage', to: 'users#commentpage'
  end
  resources :tags #do

  #resources :users ,only: [:create, :destroy]


  #get "show_articles" => "articles#show_articles"
  #get "following_tags" => "tag#following_tags"
  #resouces :articles do
    #resources :comments, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :stocks, dependent: :destroy
  has_many :users, through: :stocks
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes
  belongs_to :user
  has_many :comments

  acts_as_taggable
  acts_as_taggable_on :articles

# いいね機能実装のための記述
  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def stock_user(user_id)
    stocks.find_by(user_id: user_id)
  end

end

app/models/comment.rb
class Comment < ApplicationRecord

#アソシエーション
  belongs_to :user
  belongs_to :article

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ApplicationRecord
#アソシエーション
  belongs_to :user
# likecountの実装
  belongs_to :article, counter_cache: :likes_count
  validates :user_id, presence: true
  validates :article_id, presence: true
  validates_uniqueness_of :article_id, scope: :user_id
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/stock.rb
class Stock < ApplicationRecord

#アソシエーション
  belongs_to :user
  belongs_to :article

  def stock_user(user_id)
    stocks.find_by(user_id: user_id)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #アソシエーション
  has_many :stocks, dependent: :destroy
  has_many :articles, through: :stocks
  has_many :likes, dependent: :destroy
  has_many :articles, through: :likes
  has_many :articles
  has_many :comments
  # likescount
  has_many :likes, dependent: :destroy
  #フォロー機能
  acts_as_followable # フォロワー機能
  acts_as_follower   # フォロー機能

  #タグ機能
  acts_as_taggable
  acts_as_taggable_on :articles

  mount_uploader :image, ImageUploader

end

app/helpers/application_helper.rb
module ApplicationHelper
  def qiita_markdown(markdown)
    processor = Qiita::Markdown::Processor.new(hostname: "example.com")
    processor.filters << HTML::Pipeline::ImageMaxWidthFilter
    processor.call(markdown)[:output].to_s.html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def form_posted_time(time)
    time_d = time + 9.hour
    time_d.strftime("%Y-%m-%d %H:%M ")
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/tag_feed_helper.rb
module TagFeedHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/timeline_helper.rb
module TimelineHelper
end

app/helpers/trend_helper.rb
module TrendHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title QiitaX28
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/layouts/main.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title QiitaX28
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'shared/header', locals: { search: @search }
    = yield

app/views/shared/_header.html.haml
/ 各単語(Qiita,ホーム、コミュニティetc)の場所にリンクを記述すれば飛べるはず
/ クリックしたら一覧表示する記述が（ ）の場所予定。書くべきhamlは下にほぼ完成形あります。jsなしで行けそうだけど検索してもわからず。
/ 記述haml内にもコメントアウトあります

.header
  .short-header
    .short-header-container
      .short-header-container_left
        .title
          = link_to image_tag("header_logo.png"), root_path, class: "title_logo"
        .home
          %details
            %summary
            %ul
              .articles_trend
                = link_to "", trend_path
              .articles_timeline
                = link_to "", timeline_path
              .articles_tag-feed
                = link_to "", tag_feed_path
        .community
          %details
            %summary
            %ul
              .user_list
              .organizations
              .calendar
              .hr
              .qiitadon
              .hr
              .community_guide
              .manual
        .search
          = search_form_for search, url: articles_search_path do |f|
            = f.text_field :title_or_body_cont, placeholder: "キーワードを入力", class: "messageform"
            .search-icon
        / .search
        /   .search_megane
        /   .search_input
        /     %input{ class: "messageform", placeholder: 'キーワードを入力', type: 'search'}
      - if user_signed_in?
        .short-header-container_right
          = link_to "", articles_stocks_path, class: "stock"
          = link_to "", new_article_path, class: "postbutton"
          / .notification
          .login-user
            %details
              %summary
                .user_arrow
                - if current_user.image.blank?
                  = image_tag "no-image.png", class: "profile_picture", alt:""
                - else
                  = image_tag "#{current_user.image}", class: "profile_picture", alt:"プロフ画"
              %ul
                .mypage
                  = link_to "", user_path(id: current_user.id)
                .hr
                .draft
                .request
                .hr
                .setting
                .help
                .hr
                .logout
                  = link_to "", destroy_user_session_path, method: :delete
      - else
        .short-header-container_right
          .signin
          = link_to "", new_user_registration_path, class: "signup_button"
          .login
          = link_to "", new_user_session_path, class: "login_button"