config/routes.rb
Rails.application.routes.draw do
  resources :pages
  devise_for :users
  root 'trend#show'

  get 'trend' => 'trend#show'
  get 'timeline' => 'timeline#show'
  get 'tag_feed' => 'tag_feed#show'
  get '/application/search', to: 'application#search'
  get '/articles/search', to: 'articles#search'
  get '/articles/stocks', to: 'articles#stocks'
  get '/articles/stocks_search', to: 'articles#stocks_search'
  resources :articles do
    resources :stocks, only: [:create, :update, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users do
    get '/like', to: 'users#like'
    get '/private', to: 'users#private'
    get '/commentpage', to: 'users#commentpage'
  end
  resources :tags #do

  #resources :users ,only: [:create, :destroy]


  #get "show_articles" => "articles#show_articles"
  #get "following_tags" => "tag#following_tags"
  #resouces :articles do
    #resources :comments, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :stocks, dependent: :destroy
  has_many :users, through: :stocks
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes
  belongs_to :user
  has_many :comments

  acts_as_taggable
  acts_as_taggable_on :articles

# いいね機能実装のための記述
  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def stock_user(user_id)
    stocks.find_by(user_id: user_id)
  end

end

app/models/comment.rb
class Comment < ApplicationRecord

#アソシエーション
  belongs_to :user
  belongs_to :article

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ApplicationRecord
#アソシエーション
  belongs_to :user
# likecountの実装
  belongs_to :article, counter_cache: :likes_count
  validates :user_id, presence: true
  validates :article_id, presence: true
  validates_uniqueness_of :article_id, scope: :user_id
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/stock.rb
class Stock < ApplicationRecord

#アソシエーション
  belongs_to :user
  belongs_to :article

  def stock_user(user_id)
    stocks.find_by(user_id: user_id)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #アソシエーション
  has_many :stocks, dependent: :destroy
  has_many :articles, through: :stocks
  has_many :likes, dependent: :destroy
  has_many :articles, through: :likes
  has_many :articles
  has_many :comments
  # likescount
  has_many :likes, dependent: :destroy
  #フォロー機能
  acts_as_followable # フォロワー機能
  acts_as_follower   # フォロー機能

  #タグ機能
  acts_as_taggable
  acts_as_taggable_on :articles

  mount_uploader :image, ImageUploader

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_article, only: [:create, :destroy]

  def create
    @like = Like.create(user_id: current_user.id, article_id: params[:article_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, article_id: params[:article_id])
    like.destroy
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  layout "main"

  before_action :move_to_session, except: :index

  def show
    @tag = params[:id]
    @tags = ActsAsTaggableOn::Tag.all
    @articles = Article.all
  end

  def move_to_session
    redirect_to "/users/sign_in" unless user_signed_in?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def qiita_markdown(markdown)
    processor = Qiita::Markdown::Processor.new(hostname: "example.com")
    processor.filters << HTML::Pipeline::ImageMaxWidthFilter
    processor.call(markdown)[:output].to_s.html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def form_posted_time(time)
    time_d = time + 9.hour
    time_d.strftime("%Y-%m-%d %H:%M ")
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/tag_feed_helper.rb
module TagFeedHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/timeline_helper.rb
module TimelineHelper
end

app/helpers/trend_helper.rb
module TrendHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tags/_stock.html.haml
.stock
  - stocks = []
  - for stock in article.stocks
    - if stock.user_id == current_user.id
      - stocks << stock.id
      - id = stock.id
  - if stocks.length > 0
    = button_to article_stock_path(id: id, article_id: article.id), method: :delete, class: "btn-bg", remote: true do
      = image_tag "stock_button_on.png", class:"stock-button", alt:""
  - else
    = button_to article_stocks_path(article_id: article.id), method: :post, class: "btn-bg", remote: true do
      = image_tag "stock_button_off.png", class:"stock-button", alt:""

app/views/tags/_tag_follow.html.haml
- if tags.include?(@tag)
  - tags.delete(@tag)
  .btn
    = link_to user_path(name: current_user.name, email: current_user.email, tag: tags, this_tag: @tag, judge: 0, user: {image: current_user.image}), method: :patch, remote: true do
      = image_tag "unfollow_tag_off.png", class:"unfollow", alt:""
- else
  - tags << @tag
  .btn
    = link_to user_path(name: current_user.name, email: current_user.email, tag: tags, this_tag: @tag, judge: 0, user: {image: current_user.image}), method: :patch, remote: true do
      = image_tag "follow_tag_off.png", class:"follow", alt:""

app/views/tags/show.html.haml
- tags = []
- current_user.taggings.each do |tagging|
  - tags << tagging.tag.name
- for tag in @tags
  - if tag.name == @tag
    - this_tag = tag

.show-tag
  .content-left
    .title
      .tag-icon
      .tag-name
        %h1
          = this_tag.name
      .follow-btn
        %span{id: "tag-follow-btn"}
          = render partial: 'tag_follow', locals: { tags: tags, tag: @tag }
    .count
      .posts
        .posts-count
          - posts_count = []
          - for tagging in this_tag.taggings
            - if tagging.taggable_type == "Article"
              - posts_count << tagging.taggable_type
          = posts_count.length
        .title
          = "投稿"
      .followers
        .followers-count
          - followers_count = []
          - for tagging in this_tag.taggings
            - if tagging.taggable_type == "User"
              - followers_count << tagging.taggable_type
          = followers_count.length
        .title
          = "フォロワー"
      .explanation
        = "#{@tag}に関する情報が集まっています。現在#{posts_count.length}件の投稿があります。また#{followers_count.length}人のユーザーが#{@tag}タグをフォローしています。"
    .articles
      - taggings = []
      - articles = []
      - for tagging in this_tag.taggings
        - if tagging.taggable_type == "Article"
          - taggings << tagging.taggable_id
      - for article in @articles
        - if taggings.include?(article.id)
          - articles << article
      .liked-articles
        - articles.sort! do |a, b|
          - b[:likes_count] <=> a[:likes_count]
        .top
          = "いいねされた投稿"
        .contents
          - articles.each do |article|
            .article-tag
              .author-avatar
                - if article.user.image.blank?
                  = image_tag "no-image.png", class: "avatar", alt:""
                - else
                  = image_tag "#{article.user.image}", class: "avatar", alt:"プロフ画"
              .content
                .author
                  %span.author-name
                    = link_to article.user.name, "/#{article.user.name}", class: "author-name"
                  %span.date
                    が
                    = "#{article.created_at.strftime('%-m月%d日')}"
                    に投稿
                .content-title
                  = link_to article.title, "/articles/#{article.id}", :target=>["_blank"], class: "title-text"
                .stock-and-tags
                  %span{id: "stock-of-#{article.id}"}
                    = render partial: 'stock', locals: { article: article }
                  .tags
                    %ul
                      - article.tags.each do |tag|
                        %li.tag
                          = link_to tag.name, "/tags/#{tag.name}", class: "tag-name"
      .newest-articles
        - articles.sort! do |a, b|
          - b[:id] <=> a[:id]
        .top
          = "新着投稿"
        .contents
          - articles.each do |article|
            .article-tag
              .author-avatar
                - if article.user.image.blank?
                  = image_tag "no-image.png", class: "avatar", alt:""
                - else
                  = image_tag "#{article.user.image}", class: "avatar", alt:"プロフ画"
              .content
                .author
                  %span.author-name
                    = link_to article.user.name, "/#{article.user.name}", class: "author-name"
                  %span.date
                    が
                    = "#{article.created_at.strftime('%-m月%d日')}"
                    に投稿
                .content-title
                  = link_to article.title, "/articles/#{article.id}", :target=>["_blank"], class: "title-text"
                .stock-and-tags
                  %span{id: "stock-of-#{article.id}"}
                    = render partial: 'stock', locals: { article: article }
                  .tags
                    %ul
                      - article.tags.each do |tag|
                        %li.tag
                          = link_to tag.name, "/tags/#{tag.name}", class: "tag-name"

  .content-right